name: Artumis
title: Artumis
description: Your creativity - laser focused & amplified
theme: null

plugins:
  - jekyll-seo-tag

include: 
    - /_resources

# Build settings
sass:
  sass_dir: _sass
  style: compressed
